"""add_linked_recipe_id_to_ingredients

Revision ID: 1c9efa7d1ef1
Revises: 
Create Date: 2025-11-29 13:59:14.834661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '1c9efa7d1ef1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('linked_recipe_id', models.GUID(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'recipes', ['linked_recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'linked_recipe_id')
    # ### end Alembic commands ###
