"""remove_linked_recipe_id_from_ingredients

Revision ID: d8982b222726
Revises: db12a5307b47
Create Date: 2025-11-29 17:39:55.954578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8982b222726'
down_revision: Union[str, None] = 'db12a5307b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingredient_items_linked_recipe_id_fkey'), 'ingredient_items', type_='foreignkey')
    op.drop_column('ingredient_items', 'linked_recipe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_items', sa.Column('linked_recipe_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ingredient_items_linked_recipe_id_fkey'), 'ingredient_items', 'recipes', ['linked_recipe_id'], ['id'])
    # ### end Alembic commands ###
